config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'portfolios#index'

  resources :portfolios, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :portfolios
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @portfolios = Portfolio.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortFolioHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#"><%= image_tag 'logo.png', class: 'navbar-logo' %></a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link' %></li>
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to 'New Portfolio', new_portfolio_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
            <% else %>
              <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/portfolios/index.html.erb
<h1 class="mb-4">Portfolios</h1>

<div class="row">
  <% @portfolios.each do |portfolio| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow">
        <div class="card-body">
          <h2 class="card-title"><%= link_to portfolio.title, portfolio_path(portfolio) %></h2>
          <p class="card-text"><%= portfolio.description %></p>
          <a href="<%= portfolio.url %>" class="btn btn-primary">Visit Portfolio</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/portfolios/new.html.erb
<%= form_with model: @portfolio, local: true, html: { class: 'mb-4' } do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/portfolios/show.html.erb
<div class="card mb-4 shadow">
  <div class="card-body">
    <h1 class="card-title"><%= @portfolio.title %></h1>
    <p class="card-text"><%= @portfolio.description %></p>
    <a href="<%= @portfolio.url %>" class="btn btn-primary">Visit Portfolio</a>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>